### PR TITLE
add debug mode

### PR DESCRIPTION
**Pull request by tjjfvi**
Adds a `-d` flag to the `run` command that prints the state of the net after each reduction.

I don't know how it would be best to incorporate this logic into the current structure, but I suspect it isn't what is written here; hence, draft.

<details>
<summary>Example output</summary>

```
Cons = @h @t @c @* (c h t)
Nil = @* @n n

map = @list
  (list
    @list.head @list.tail @f (Cons (f list.head) (map list.tail f))
    @* Nil
  )

main = (map (Cons 1 (Cons 2 (Cons 3 Nil))) (@x (x, x)))
```
```
((map ((Cons 1) ((Cons 2) ((Cons 3) Nil)))) λa dup b c = a; (c, b))
---------------------------------------
((map ((Cons 1) ((Cons 2) ((λa λb λc λ* ((c a) b) 3) Nil)))) λd dup e f = d; (f, e))
---------------------------------------
((map ((Cons 1) ((Cons 2) (λa λb λ* ((b 3) a) Nil)))) λc dup d e = c; (e, d))
---------------------------------------
((map ((Cons 1) ((Cons 2) λa λ* ((a 3) Nil)))) λb dup c d = b; (d, c))
---------------------------------------
((map ((Cons 1) ((λa λb λc λ* ((c a) b) 2) λd λ* ((d 3) Nil)))) λe dup f g = e; (g, f))
---------------------------------------
((map ((Cons 1) (λa λb λ* ((b 2) a) λc λ* ((c 3) Nil)))) λd dup e f = d; (f, e))
---------------------------------------
((map ((Cons 1) λa λ* ((a 2) λb λ* ((b 3) Nil)))) λc dup d e = c; (e, d))
---------------------------------------
((map ((λa λb λc λ* ((c a) b) 1) λd λ* ((d 2) λe λ* ((e 3) Nil)))) λf dup g h = f; (h, g))
---------------------------------------
((map (λa λb λ* ((b 1) a) λc λ* ((c 2) λd λ* ((d 3) Nil)))) λe dup f g = e; (g, f))
---------------------------------------
((map λa λ* ((a 1) λb λ* ((b 2) λc λ* ((c 3) Nil)))) λd dup e f = d; (f, e))
---------------------------------------
((λa ((a λb λc λd dup e f = d; ((Cons (f b)) ((map c) e))) λ* Nil) λg λ* ((g 1) λh λ* ((h 2) λi λ* ((i 3) Nil)))) λj dup k l = j; (l, k))
---------------------------------------
(((λa λ* ((a 1) λb λ* ((b 2) λc λ* ((c 3) Nil))) λd λe λf dup g h = f; ((Cons (h f)) ((map e) g))) λ* Nil) λi dup j k = i; (k, j))
---------------------------------------
((λ* ((λa λb λc dup d e = c; ((Cons (e a)) ((map b) d)) 1) λf λ* ((f 2) λg λ* ((g 3) Nil))) λ* Nil) λh dup i j = h; (j, i))
---------------------------------------
(((λa λb λc dup d e = c; ((Cons (e a)) ((map b) d)) 1) λf λ* ((f 2) λg λ* ((g 3) Nil))) λh dup i j = h; (j, i))
---------------------------------------
(((λa λb λc ((Cons (c a)) ((map b) c)) 1) λd λ* ((d 2) λe λ* ((e 3) Nil))) λf dup g h = f; (h, g))
---------------------------------------
((λa λb ((Cons (b 1)) ((map a) b)) λc λ* ((c 2) λd λ* ((d 3) Nil))) λe dup f g = e; (g, f))
---------------------------------------
(λa ((Cons (a 1)) ((map λb λ* ((b 2) λc λ* ((c 3) Nil))) a)) λd dup e f = d; (f, e))
---------------------------------------
((Cons (λa dup b c = a; (c, b) 1)) ((map λd λ* ((d 2) λe λ* ((e 3) Nil))) λf dup g h = f; (h, g)))
---------------------------------------
((Cons (λa (a, a) 1)) ((map λb λ* ((b 2) λc λ* ((c 3) Nil))) λa (a, a)))
---------------------------------------
((Cons (λa (a, a) 1)) ((map λb λ* ((b 2) λc λ* ((c 3) Nil))) λd (d, d)))
---------------------------------------
((Cons (1, 1)) ((map λa λ* ((a 2) λb λ* ((b 3) Nil))) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((map λa λ* ((a 2) λb λ* ((b 3) Nil))) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((map λa λ* ((a 2) λb λ* ((b 3) Nil))) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((map λa λ* ((a 2) λb λ* ((b 3) Nil))) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((map λa λ* ((a 2) λb λ* ((b 3) Nil))) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((map λa λ* ((a 2) λb λ* ((b 3) Nil))) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((λa ((a λb λc λd dup e f = d; ((Cons (f b)) ((map c) e))) λ* Nil) λg λ* ((g 2) λh λ* ((h 3) Nil))) λi (i, i)))
---------------------------------------
((Cons (1, 1)) (((λa λ* ((a 2) λb λ* ((b 3) Nil)) λc λd λe dup f g = e; ((Cons (g c)) ((map e) f))) λ* Nil) λh (h, h)))
---------------------------------------
((Cons (1, 1)) ((λ* ((λa λb λc dup d e = c; ((Cons (e a)) ((map b) d)) 2) λf λ* ((f 3) Nil)) λ* Nil) λg (g, g)))
---------------------------------------
((Cons (1, 1)) (((λa λb λc dup d e = c; ((Cons (e a)) ((map b) d)) 2) λf λ* ((f 3) Nil)) λg (g, g)))
---------------------------------------
((Cons (1, 1)) (((λa λb λc ((Cons (c a)) ((map b) c)) 2) λd λ* ((d 3) Nil)) λe (e, e)))
---------------------------------------
((Cons (1, 1)) ((λa λb ((Cons (b 2)) ((map a) b)) λc λ* ((c 3) Nil)) λd (d, d)))
---------------------------------------
((Cons (1, 1)) (λa ((Cons (a 2)) ((map λb λ* ((b 3) Nil)) a)) λc (c, c)))
---------------------------------------
((Cons (1, 1)) ((Cons (λa (a, a) 2)) ((map λb λ* ((b 3) Nil)) λa (a, a))))
---------------------------------------
((Cons (1, 1)) ((Cons (λa (a, a) 2)) ((map λb λ* ((b 3) Nil)) λc (c, c))))
---------------------------------------
((Cons (1, 1)) ((Cons (λa (a, a) 2)) ((map λb λ* ((b 3) Nil)) λc (c, c))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((map λa λ* ((a 3) Nil)) λb (b, b))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((map λa λ* ((a 3) Nil)) λb (b, b))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((map λa λ* ((a 3) Nil)) λb (b, b))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((map λa λ* ((a 3) Nil)) λb (b, b))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((map λa λ* ((a 3) Nil)) λb (b, b))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((λa ((a λb λc λd dup e f = d; ((Cons (f b)) ((map c) e))) λ* Nil) λg λ* ((g 3) Nil)) λh (h, h))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) (((λa λ* ((a 3) Nil) λb λc λd dup e f = d; ((Cons (f b)) ((map c) e))) λ* Nil) λg (g, g))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((λ* ((λa λb λc dup d e = c; ((Cons (e a)) ((map b) d)) 3) Nil) λ* Nil) λf (f, f))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) (((λa λb λc dup d e = c; ((Cons (e a)) ((map b) d)) 3) Nil) λf (f, f))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) (((λa λb λc ((Cons (c a)) ((map b) c)) 3) Nil) λd (d, d))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((λa λb ((Cons (b 3)) ((map a) b)) Nil) λc (c, c))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) (λa ((Cons (a 3)) ((map Nil) a)) λb (b, b))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (λa (a, a) 3)) ((map Nil) λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (λa (a, a) 3)) ((map Nil) λb (b, b)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (λa (a, a) 3)) ((map Nil) λb (b, b)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((map Nil) λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((map Nil) λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((map Nil) λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((map Nil) λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((map Nil) λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((λa ((a λb λc λd dup e f = d; ((Cons (f b)) ((map c) e))) λ* Nil) Nil) λg (g, g)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) (((Nil λa λb λc dup d e = c; ((Cons (e a)) ((map b) d))) λ* Nil) λf (f, f)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) (((λ* λa a λb λc λd dup e f = d; ((Cons (f b)) ((map c) e))) λ* Nil) λg (g, g)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((λa a λ* Nil) λb (b, b)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) ((λa a λ* Nil) λb (b, b)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) (λ* Nil λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) (λ* Nil λa (a, a)))))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((Cons (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) ((λa λb λc λ* ((c a) b) (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) (λa λb λ* ((b (3, 3)) a) Nil)))
---------------------------------------
((Cons (1, 1)) ((Cons (2, 2)) λa λ* ((a (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) ((λa λb λc λ* ((c a) b) (2, 2)) λd λ* ((d (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) (λa λb λ* ((b (2, 2)) a) λc λ* ((c (3, 3)) Nil)))
---------------------------------------
((Cons (1, 1)) λa λ* ((a (2, 2)) λb λ* ((b (3, 3)) Nil)))
---------------------------------------
((λa λb λc λ* ((c a) b) (1, 1)) λd λ* ((d (2, 2)) λe λ* ((e (3, 3)) Nil)))
---------------------------------------
(λa λb λ* ((b (1, 1)) a) λc λ* ((c (2, 2)) λd λ* ((d (3, 3)) Nil)))
---------------------------------------
λa λ* ((a (1, 1)) λb λ* ((b (2, 2)) λc λ* ((c (3, 3)) λ* λd d)))
```
</details>

### CODE REVIEW

**Comment by developedby** [comment]
I think the way you did it is good, maybe we could go even more granular and print every reduction.
The only thing I'd like to see is if this change affects the performance for non-debug execution.

**Comment by tjjfvi** [comment]
> I think the way you did it is good, maybe we could go even more granular and print every reduction.

What do you mean? Like printing `--------------- DUP-CTR` after each step?

**Comment by developedby** [comment]
Sorry, just noticed that `reduce` now can receive the number of reductions to do, so this is already going one reduction per step (plus expanding).

**Comment by developedby** [comment]
I've rebased and reformatted this a bit in #71

**Pull request closed without merging**
